apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp
images:
- name: goapp
  newName: ericsonmessias/goapp
  newTag: 4582e7b5ffcd2f3abf42295e13204f010a7ffd47
